---
# tasks file for sonic-pi

- name: Starting Sonic-Pi tasks
  debug:
    msg: "Starting Sonic-Pi tasks"

- name: Set configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ user.home }}/.sonic-pi/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - audio-settings.toml
    - colour-theme.properties
    - init.rb

- name: Install helpers and snippets
  copy:
    src: helpers/
    dest: "{{ user.home }}/.sonic-pi/"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
    # directory_mode:

- name: Clone ziffers repository
  git:
    repo:
    dest: "{{ user.home }}/.sonic-pi/ziffers"
    recursive: yes
    accept_hostkey: yes
    update: no
    force: no
  check_mode: no
