galaxy_info:
  author: your name
  description: your role description
  company: your company (optional)

  license: MIT

  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: ArchLinux
      versions:
        - all
    #- name: AlmaLinux
    #  versions:
    #    - "9.3"
    #- name: Fedora
    #  versions:
    #    - "37"
    #- name: Debian
    #  versions:
    #    - "bookworm"

  galaxy_tags:
    - linux-audio

dependencies:
  []
  # - common
  # - ruby
  # - terminal
  # - audio
  # - network
