---
admin_group: wheel

repos_chaotic: True
repos_syncopated: False
# syncopated:
#     mirrors:
#   "http://bender.syncopated.net/syncopated/repo"
      #  "http://syncopated.hopto.org/syncopated/repo"

chaoticrepo: True

IgnorePkg: "ncurses lib32-ncurses gitui"

distro__packages:
  - archlinux-xdg-menu

base_packages:
#    - ascii-image-converter
  - asciiquarium-git
  - aspell
  - aspell-en
  - atool
  - audiofile
  - autofs
  - await
  - bandwhich
  - bash-completion
  - bash-language-server
  - bat
  - beautysh
  - bottom
  - choose
  - chromaprint
  - cmake
  - cpupower
  - curlie
  - dex
  - doggo
  - downgrade
  - duf
  - dust
  - elinks
  - eza
  - faac
  - faad2
  - fd
  - figlet
  - firewalld
  - fsarchiver
  - fuse3
  - fuse-common
  - git
  - git-delta
  - git-lfs
  - github-cli
  - gitui
  - glow
  - gnome-keyring
  - gnuplot
  - gource
  - gping
  - graphicsmagick
  - gst-libav
  - gstreamer
  - gum
  - highlight
  - hspell
  - htop
  - i7z
  - imagemagick
  - inetutils
  - inxi
  - iotop
  - jq
  - libcyaml
  - libgit2
  - libgit2-glib
  - libvips
  - libvoikko
  - links
  - lnav
  - lynx
  - mako
  - mediainfo
  - meld
  - micro
  - mlocate
  - most
  - mupdf-tools
  - nano-syntax-highlighting
  - ncdu
  - net-tools
  - nodejs
  - npm
  - numlockx
  - nuspell
  - odt2txt
  - openssl
  - opus
  - opus-tools
  - opusfile
  - pamixer
  - pandoc-cli
  - pdf2htmlex-appimage
  - pdfjs
  - perl-image-exiftool
  - pgvector
  - platformfolders
  - playerctl
  - pod2man
  - poppler
  - postgresql-libs
  - poweralertd
  - python-adblock
  - python-chardet
  - python-j2cli
  - python-pagelabels
  - python-pillow
  - python-pygments
  - python-pympler
  - python-setuptools
  - python-sphinx-intl
  - python-sphinxcontrib-svg2pdfconverter
  - qpdf
  - ranger
  - ripgrep
  - ripgrep-all
  - rsync
  - rxvt-unicode
  - sd
  - smartmontools
  - socat
  - speech-dispatcher
  - sshpass
  - stunnel
  - sudo
  - swappy
  - sysstat
  - taglib
  - teiler-git
  - texlive-basic
  - texlive-bin
  # - texlive-doc
  # - texlive-fontsextra
  # - texlive-fontsrecommended
  # - texlive-latex
  # - texlive-latexextra
  # - texlive-latexrecommended
  # - texlive-pictures
  # - texlive-xetex
  - tldr
  - transmission-cli
  - tree
  - ueberzug
  - unrar
  - unzip
  - v4l-utils
  - vorbis-tools
  - wavpack
  - wget
  - wkhtmltopdf-static
  - wmctrl
  - wordnet-cli
  - wordnet-common
  - x264
  - x265
  - xterm
  - yad
  - yt-dlp
  - zoxide

desktop_packages:
  - arandr
  - broot
  - btop
  - calcurse
  - cbonsai
  - dconf
  - devdocs-desktop
  - dunst
  - feh
  - gedit
  - gedit-markdownpreview-git
  - gedit-plugins
  - gedit-smart-home
  - geoclue
  - gnu-free-fonts
  - google-chrome
  - gpick
  - gtk-update-icon-cache
  - gucharmap
  - gummi
  - gvfs-smb
  - imv
  - keepassxc
  - maim
  - metagedit-git
  - mpv
  - nitrogen
  - nvtop
  - obsidian
  - openscad
  - openslide
  # - pgmodeler
  - qpdfview
  # - radiotray-ng
  - seahorse
  - shotcut
  - sxiv
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - timeshift
  - vlc
  - wmfocus
  - wordnet-tk
  - zenity

docker_packages:
  - docker
  - docker-compose
  - lazydocker-bin

x11_packages:
  - dunst
  - picom
  - xarchiver
  - xclip
  - xcursor-breeze
  - xdot
  - xdotool
  - xf86-input-libinput
  - xf86-input-wacom
  - xf86-video-fbdev
  - xf86-video-intel
  - xf86-video-vesa
  - xkill-shortcut
  - xob
  - xorg-bdftopcf
  - xorg-fonts-alias-75dpi
  - xorg-fonts-alias-100dpi
  - xorg-fonts-alias-cyrillic
  - xorg-fonts-alias-misc
  - xorg-fonts-misc
  - xorg-iceauth
  - xorg-mkfontscale
  - xorg-server
  - xorg-sessreg
  - xorg-setxkbmap
  - xorg-smproxy
  - xorg-x11perf
  - xorg-xauth
  - xorg-xbacklight
  - xorg-xcmsdb
  - xorg-xcursorgen
  - xorg-xdpyinfo
  - xorg-xdriinfo
  - xorg-xev
  - xorg-xgamma
  - xorg-xhost
  - xorg-xinit
  - xorg-xinput
  - xorg-xkbcomp
  - xorg-xkbevd
  - xorg-xkbutils
  - xorg-xkill
  - xorg-xlsatoms
  - xorg-xlsclients
  - xorg-xlsfonts
  - xorg-xmodmap
  - xorg-xpr
  - xorg-xprop
  - xorg-xrandr
  - xorg-xrdb
  - xorg-xrefresh
  - xorg-xset
  - xorg-xsetroot
  - xorg-xvinfo
  - xorg-xwd
  - xorg-xwininfo
  - xorg-xwud

tuning_packages:
  - x86_energy_perf_policy
  - cpupower
  - rtirq
  - rtkit
  - tuned
  - irqbalance
  - linux-headers

theme_packages:
  - arc-icon-theme
  - awesome-terminal-fonts
  - breeze-gtk
  - cantarell-fonts
  - gedit-dark-variant
  - kvantum
  - kvantum-qt5
  - kvantum-theme-matcha
  - matcha-gtk-theme
  - mojave-gtk-theme
  - noto-color-emoji-fontconfig
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  # - numix-circle-icon-theme-git
  # - numix-icon-theme-git
  - open-chinese-fonts
  - opendesktop-fonts
  - qscintilla-qt5
  - qt5-base
  - qt5-declarative
  - qt5-graphicaleffects
  - qt5-location
  - qt5-quickcontrols2
  - qt5-tools
  - qt5-x11extras
  - qt5ct
  - qt6-base
  - qt6-declarative
  - qt6-multimedia
  - qt6-tools
  - qt6ct
  - ttf-bitstream-vera
  - ttf-dejavu
  - ttf-devicons
  - ttf-firacode-nerd
  - ttf-font-awesome
  - ttf-input
  - ttf-jetbrains-mono
  - ttf-liberation
  - ttf-meslo-nerd
  - ttf-opensans
  - ttf-ubuntu-font-family

daw_packages:
  - ambdec
  # - ambix-o1
  # - ambix-o3
  # - ambix-o5
  - audacity
  # - baudline-bin
  # - bipscript
  # - bipscript-ide
  - bitwig-studio
  - calf
  # - caps-lv2-git
  - carla
  # - cpod-appimage
  - darktable
  - distrho-ports
  - distrho-ports-lv2
  - distrho-ports-vst
  - distrho-ports-vst3
  # - djvulibre
  - dragonfly-reverb
  - dragonfly-reverb-clap
  - dragonfly-reverb-lv2
  - dragonfly-reverb-standalone
  - dragonfly-reverb-vst
  - dragonfly-reverb-vst3
  # - drumrox
  # - ecasound
  # - ffmpeg4.4
  - ffmpegthumbnailer
  - fftw
  - fluidsynth
  - fontforge
  # - geonkick
  # - geonkick-common
  # - geonkick-lv2
  # - geonkick-standalone
  # - gimp
  # - helm-synth
  # - helm-synth-common
  # - helm-synth-lv2
  # - helm-synth-standalone
  # - helm-synth-vst
  # - hydrogen-git
  - iempluginsuite
  # - ingen-git
  # - intersect.lv2-git
  - jaaa
  - jalv
  - jalv-select
  - japa
  - jc
  - jconvolver
  - jnoisemeter
  - ladspa
  - lame
  - libaudec
  - libcaca
  - linuxsampler
  - lsp-dsp-lib
  - lv2-c++-tools
  # - mcfx-o1
  # - mcfx-o3
  # - mcfx-o5
  - mediamtx
  # - midieditor
  - mixxx
  - mtr
  # - non-mixer-lv2-git
  # - non-sequencer
  - glib2-devel
  - ocenaudio-bin
  - patchage
  - patchance
  - qmidinet
  - qsampler
  # - raul
  - raysession
  - rnnoise
  - rtaudio
  - rtmidi
  - sc3-plugins
  # - scala-music
  # - scala-music-scales
  - sendmidi
  - sonic-pi-git
  - sonic-visualiser
  # - sonic-visualiser-git
  # - sononym
  # - sooperlooper-git
  - sound-gambit
  # - sparta-plugins
  - supercollider
  - swh-lv2-git
  - tap-plugins-lv2-git
  # - tonsespace
  # - vital-synth-git
  - vmpk
  - vst2sdk
  - x42-plugins
  - x42-plugins-lv2
  - x42-plugins-standalone
  - zita-ajbridge
  - zita-alsa-pcmi
  - zita-convolver
  - zita-dpl1
  - zita-lrx
  - zita-mu1
  - zita-resampler
  - zita-rev1
# alsa: audio role
# ambisonics: audio role
# analysis: audio role
# audio: audio role
# browser: desktop role
# codecs: audio role
# cursors: desktop role
# desktop: desktop role
# development: desktop role
# docs: desktop role
# fonts: desktop role
# gtk3: desktop role
# i3: desktop role
# icons: desktop role
# jack: audio role
# kvantum: desktop role
# loopers: audio role
# media: desktop role
# midi: audio role
# pipewire: audio role
# plugins: audio role
# pulseaudio: audio role
# python: desktop role
# qt5: desktop role
# qt6: desktop role
# ruby: ruby role
# samplers: audio role
# sequencers: audio role
# sway: desktop role
# synths: audio role
# terminal: terminal role
# themes: desktop role
# tools: audio role
# utility: desktop role
# xorg: x role
