---

- name: Collect only selected facts
  setup:
    filter:
      - 'ansible_processor'

- name: Create /etc/xdg/menus and /usr/share/desktop-entries
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/xdg/menus
    - /etc/xdg/menus/applications-merged
    - /etc/xdg/Thunar
    - /usr/share/desktop-directories

- name: Install application menu
  copy:
    src: "files/etc/xdg/menus/arch-applications.menu"
    dest: "/etc/xdg/menus/arch-applications.menu"
    mode: '0644'
    backup: yes
  tags: ['menu']

- name: Install menus
  copy:
    src: "files/etc/xdg/menus/applications-merged/{{ item }}"
    dest: "/etc/xdg/menus/applications-merged/{{ item }}"
    mode: '0644'
  with_items:
    # - ambix.menu
    - dragonfly.menu
    - iempluginsuite.menu
    # - lsp-plugins.menu
    # - mcfx.menu
  tags: ['menu']

- name: Install directory entries
  copy:
    src: "files/usr/local/share/desktop-directories/{{ item }}"
    dest: "/usr/share/desktop-directories/{{ item }}"
    mode: '0644'
    backup: no
  with_items:
    - Ambisonics.directory
    # - ambix.directory
    - Audio.directory
    - dragonfly.directory
    - iempluginsuite.directory
    # - lsp-plugins.directory
    # - mcfx.directory
  tags: ['menu']

- name: Install Ambisonics desktop entries
  ansible.posix.synchronize:
    src: "files/usr/local/share/applications/{{ item }}/"
    dest: "/usr/share/applications/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
  loop:
    # - ambisonics/ambix
    # - ambisonics/mcfx
    - ambisonics/iempluginsuite
    - dragonfly
    - x42
  tags: ['desktop']

# - name: Install mcfx entries
#   copy:
#     src: "usr/local/share/applications/ambisonics/mcfx/{{ item }}"
#     dest: "/usr/share/applications/{{ item }}"
#     mode: '0644'
#     backup: no
#   with_items:
#       - mcfx_convolver_o1.desktop
#       - mcfx_convolver_o3.desktop
#       - mcfx_convolver_o5.desktop
#       - mcfx_delay_o1.desktop
#       - mcfx_delay_o3.desktop
#       - mcfx_delay_o5.desktop
#       - mcfx_filter_o1.desktop
#       - mcfx_filter_o3.desktop
#       - mcfx_filter_o5.desktop
#       - mcfx_gain_delay_o1.desktop
#       - mcfx_gain_delay_o3.desktop
#       - mcfx_gain_delay_o5.desktop
#       - mcfx_meter_o1.desktop
#       - mcfx_meter_o3.desktop
#       - mcfx_meter_o5.desktop
#   tags: ['mcfx', 'ambix']
#
# - name: Install iempluginsuite entries
#   copy:
#     src: "usr/local/share/applications/ambisonics/iempluginsuite/{{ item }}"
#     dest: "/usr/share/applications/{{ item }}"
#     mode: '0644'
#     backup: no
#   with_items:
#     - at.iem.plugins.AllRADecoder.desktop
#     - at.iem.plugins.BinauralDecoder.desktop
#     - at.iem.plugins.CoordinateConverter.desktop
#     - at.iem.plugins.DirectionalCompressor.desktop
#     - at.iem.plugins.DirectivityShaper.desktop
#     - at.iem.plugins.DistanceCompensator.desktop
#     - at.iem.plugins.DualDelay.desktop
#     - at.iem.plugins.EnergyVisualizer.desktop
#     - at.iem.plugins.FdnReverb.desktop
#     - at.iem.plugins.MatrixMultiplier.desktop
#     - at.iem.plugins.MultiBandCompressor.desktop
#     - at.iem.plugins.MultiEncoder.desktop
#     - at.iem.plugins.MultiEQ.desktop
#     - at.iem.plugins.OmniCompressor.desktop
#     - at.iem.plugins.PluginTemplate.desktop
#     - at.iem.plugins.ProbeDecoder.desktop
#     - at.iem.plugins.RoomEncoder.desktop
#     - at.iem.plugins.SceneRotator.desktop
#     - at.iem.plugins.SimpleDecoder.desktop
#     - at.iem.plugins.StereoEncoder.desktop
#     - at.iem.plugins.ToolBox.desktop
#   tags: ['iempluginsuite']
#
# - name: Install x42 entries
#   copy:
#     src: "usr/local/share/applications/x42/{{ item }}"
#     dest: "/usr/share/applications/{{ item }}"
#     mode: '0644'
#     backup: no
#   with_items:
#     - com.x42_plugins.x42_darc.desktop
#     - com.x42_plugins.x42_dpl.desktop
#     - com.x42_plugins.x42_fat1.desktop
#     - com.x42_plugins.x42_fil4.desktop
#     - com.x42_plugins.x42_matrixmixer8x8.desktop
#     - com.x42_plugins.x42_meter_0.desktop
#     - com.x42_plugins.x42_meter_1.desktop
#     - com.x42_plugins.x42_meter_2.desktop
#     - com.x42_plugins.x42_meter_3.desktop
#     - com.x42_plugins.x42_meter_4.desktop
#     - com.x42_plugins.x42_meter_5.desktop
#     - com.x42_plugins.x42_meter_6.desktop
#     - com.x42_plugins.x42_meter_7.desktop
#     - com.x42_plugins.x42_meter_8.desktop
#     - com.x42_plugins.x42_meter_9.desktop
#     - com.x42_plugins.x42_meter_10.desktop
#     - com.x42_plugins.x42_meter_11.desktop
#     - com.x42_plugins.x42_meter_12.desktop
#     - com.x42_plugins.x42_meter_13.desktop
#     - com.x42_plugins.x42_meter_14.desktop
#     - com.x42_plugins.x42_meter_15.desktop
#     - com.x42_plugins.x42_meter_16.desktop
#     - com.x42_plugins.x42_meter_17.desktop
#     - com.x42_plugins.x42_meter_18.desktop
#     - com.x42_plugins.x42_meter_19.desktop
#     - com.x42_plugins.x42_mixtri.desktop
#     - com.x42_plugins.x42_phaserotate.desktop
#     - com.x42_plugins.x42_scope.desktop
#     - com.x42_plugins.x42_spectr.desktop
#     - com.x42_plugins.x42_stepseq.desktop
#     - com.x42_plugins.x42_tuna_0.desktop
#     - com.x42_plugins.x42_tuna_1.desktop
#   tags: ['x42']
#
# - name: Install Dragonfly entries
#   copy:
#     src: "usr/local/share/applications/dragonfly/{{ item }}"
#     dest: "/usr/share/applications/{{ item }}"
#     mode: '0644'
#     backup: no
#   with_items:
#     - io.github.michaelwillis.DragonflyEarlyReflections.desktop
#     - io.github.michaelwillis.DragonflyHallReverb.desktop
#     - io.github.michaelwillis.DragonflyPlateReverb.desktop
#     - io.github.michaelwillis.DragonflyRoomReverb.desktop
#   tags: ['dragonfly']

# - name: Comment out keywords in lsp desktop entries
#   lineinfile:
#     dest: "/usr/share/applications/in.lsp_plug.lsp_plugins_{{ item }}"
#     regexp: "^Keywords="
#     line: 'Categories=Audio;'
#     backrefs: yes
#     backup: no
#   with_items:
#     - art_delay_mono.desktop
#     - art_delay_stereo.desktop
#     - comp_delay_mono.desktop
#     - comp_delay_stereo.desktop
#     - comp_delay_x2_stereo.desktop
#     - compressor_lr.desktop
#     - compressor_mono.desktop
#     - compressor_ms.desktop
#     - compressor_stereo.desktop
#     - crossover_lr.desktop
#     - crossover_mono.desktop
#     - crossover_ms.desktop
#     - crossover_stereo.desktop
#     - dyna_processor_lr.desktop
#     - dyna_processor_mono.desktop
#     - dyna_processor_ms.desktop
#     - dyna_processor_stereo.desktop
#     - expander_lr.desktop
#     - expander_mono.desktop
#     - expander_ms.desktop
#     - expander_stereo.desktop
#     - gate_lr.desktop
#     - gate_mono.desktop
#     - gate_ms.desktop
#     - gate_stereo.desktop
#     - graph_equalizer_x16_lr.desktop
#     - graph_equalizer_x16_mono.desktop
#     - graph_equalizer_x16_ms.desktop
#     - graph_equalizer_x16_stereo.desktop
#     - graph_equalizer_x32_lr.desktop
#     - graph_equalizer_x32_mono.desktop
#     - graph_equalizer_x32_ms.desktop
#     - graph_equalizer_x32_stereo.desktop
#     - impulse_responses_mono.desktop
#     - impulse_responses_stereo.desktop
#     - impulse_reverb_mono.desktop
#     - impulse_reverb_stereo.desktop
#     - latency_meter.desktop
#     - limiter_mono.desktop
#     - limiter_stereo.desktop
#     - loud_comp_mono.desktop
#     - loud_comp_stereo.desktop
#     - mb_compressor_lr.desktop
#     - mb_compressor_mono.desktop
#     - mb_compressor_ms.desktop
#     - mb_compressor_stereo.desktop
#     - mb_dyna_processor_lr.desktop
#     - mb_dyna_processor_mono.desktop
#     - mb_dyna_processor_ms.desktop
#     - mb_dyna_processor_stereo.desktop
#     - mb_expander_lr.desktop
#     - mb_expander_mono.desktop
#     - mb_expander_ms.desktop
#     - mb_expander_stereo.desktop
#     - mb_gate_lr.desktop
#     - mb_gate_mono.desktop
#     - mb_gate_ms.desktop
#     - mb_gate_stereo.desktop
#     - multisampler_x12.desktop
#     - multisampler_x12_do.desktop
#     - multisampler_x24.desktop
#     - multisampler_x24_do.desktop
#     - multisampler_x48.desktop
#     - multisampler_x48_do.desktop
#     - noise_generator_x1.desktop
#     - noise_generator_x2.desktop
#     - noise_generator_x4.desktop
#     - oscillator_mono.desktop
#     - oscilloscope_x1.desktop
#     - oscilloscope_x2.desktop
#     - oscilloscope_x4.desktop
#     - para_equalizer_x16_lr.desktop
#     - para_equalizer_x16_mono.desktop
#     - para_equalizer_x16_ms.desktop
#     - para_equalizer_x16_stereo.desktop
#     - para_equalizer_x32_lr.desktop
#     - para_equalizer_x32_mono.desktop
#     - para_equalizer_x32_ms.desktop
#     - para_equalizer_x32_stereo.desktop
#     - phase_detector.desktop
#     - profiler_mono.desktop
#     - profiler_stereo.desktop
#     - room_builder_mono.desktop
#     - room_builder_stereo.desktop
#     - sampler_mono.desktop
#     - sampler_stereo.desktop
#     - sc_compressor_lr.desktop
#     - sc_compressor_mono.desktop
#     - sc_compressor_ms.desktop
#     - sc_compressor_stereo.desktop
#     - sc_dyna_processor_lr.desktop
#     - sc_dyna_processor_mono.desktop
#     - sc_dyna_processor_ms.desktop
#     - sc_dyna_processor_stereo.desktop
#     - sc_expander_lr.desktop
#     - sc_expander_mono.desktop
#     - sc_expander_ms.desktop
#     - sc_expander_stereo.desktop
#     - sc_gate_lr.desktop
#     - sc_gate_mono.desktop
#     - sc_gate_ms.desktop
#     - sc_gate_stereo.desktop
#     - sc_limiter_mono.desktop
#     - sc_limiter_stereo.desktop
#     - sc_mb_compressor_lr.desktop
#     - sc_mb_compressor_mono.desktop
#     - sc_mb_compressor_ms.desktop
#     - sc_mb_compressor_stereo.desktop
#     - sc_mb_dyna_processor_lr.desktop
#     - sc_mb_dyna_processor_mono.desktop
#     - sc_mb_dyna_processor_ms.desktop
#     - sc_mb_dyna_processor_stereo.desktop
#     - sc_mb_expander_lr.desktop
#     - sc_mb_expander_mono.desktop
#     - sc_mb_expander_ms.desktop
#     - sc_mb_expander_stereo.desktop
#     - sc_mb_gate_lr.desktop
#     - sc_mb_gate_mono.desktop
#     - sc_mb_gate_ms.desktop
#     - sc_mb_gate_stereo.desktop
#     - slap_delay_mono.desktop
#     - slap_delay_stereo.desktop
#     - spectrum_analyzer_x1.desktop
#     - spectrum_analyzer_x2.desktop
#     - spectrum_analyzer_x4.desktop
#     - spectrum_analyzer_x8.desktop
#     - spectrum_analyzer_x12.desktop
#     - spectrum_analyzer_x16.desktop
#     - surge_filter_mono.desktop
#     - surge_filter_stereo.desktop
#     - trigger_midi_mono.desktop
#     - trigger_midi_stereo.desktop
#     - trigger_mono.desktop
#     - trigger_stereo.desktop
#   tags: ['lsp']

# - name: Install desktop entries
#   copy:
#     src: "files/usr/local/share/applications/{{ item }}"
#     dest: "/usr/share/applications/{{ item }}"
#     mode: '0644'
#     backup: no
#   with_items:
    # - audacity.desktop
    # - baudline.desktop
    # - bipscript-ide.desktop
    # - calf.desktop
    # - cockos-reaper.desktop
    # - com.obsproject.Studio.desktop
    # - com.polyphone_soundfonts.polyphone.desktop
    # - fmit.desktop
    # - helm-synth.desktop
    # - jaaa.desktop
    # - jack-keyboard.desktop
    # - jack-rack.desktop
    # - jack_mixer.desktop
    # - jalv.desktop
    # - jalv.select.desktop
    # - japa.desktop
    # - monique.desktop
    # - net.essej.sooperlooper.desktop
    # - net.sourceforge.VMPK.desktop
    # - non-mixer.desktop
    # - ocenaudio.desktop
    # - org.hydrogenmusic.Hydrogen.desktop
    # - org.jacktrip.JackTrip.desktop
    # - org.mixxx.Mixxx.desktop
    # - org.rncbc.qmidinet.desktop
    # - org.rncbc.qsampler.desktop
    # - patchage.desktop
    # - pavucontrol.desktop
    # - planetccrma-snd.desktop
    # - Protokol.desktop
    # - qmidiarp.desktop
    # - radiotray-ng.desktop
    # - Scala.desktop
    # - sonic-lineup.desktop
    # - sonic-pi.desktop
    # - sonic-visualiser.desktop
    # - sononym.desktop
    # - soundbot.desktop
    # - SuperColliderIDE.desktop
    # - timemachine.desktop
    # - tony.desktop
    # - TouchOSC.desktop
    # - zita-mu1.desktop
    # - zita-rev1.desktop

# - name: xdg-user-dirs-update service
#   systemd:
#     name: xdg-user-dirs-update.service
#     enabled: yes
#     scope: user
#   environment:
#     XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
#   become_user: "{{ user.name }}"

- name: Set XDG env vars
  copy:
    content: |
      # -*- mode: shell-script -*-
      # ref: https://wiki.archlinux.org/title/XDG_Base_Directory
      ## XDG_RUNTIME_DIR defined by pam
      XDG_CONFIG_DIRS="/etc/xdg"
      XDG_DATA_DIRS="/usr/local/share/:/usr/share"
      XDG_CONFIG_HOME="$HOME/.config"
      XDG_CACHE_HOME="$HOME/.cache"
      XDG_DATA_HOME="$HOME/.local/share"
      XDG_STATE_HOME="$HOME/.local/state"
    dest: /usr/lib/environment.d/50-xdg-environment.conf
  tags: ['env', 'xdg']

- name: Install Thunar actions
  copy:
    src: "files/etc/xdg/Thunar/{{ item }}"
    dest: "/etc/xdg/Thunar/{{ item }}"
    mode: '0644'
  with_items:
    - accels.scm
    - uca.xml
  tags: ['thunar']

- name: Set Thunar as default for opening directories
  shell: xdg-mime default thunar.desktop inode/directory
  become_user: "{{ user.name }}"
  tags: ['thunar']

- name: Update desktop database
  command: bash -lc "update-desktop-database"
