---

use_bluetooth: True

# network:
#   interfaces:
#     enp2s0:
#       type: ethernet
#       ifname: enp2s0
#       conn_name: enp2s0
#       mac: 58:8a:5a:38:fb:22
#       autoconnect: False
#       state: present
#       method4: disabled
#     wlan0:
#       type: wifi
#       ifname: wlan0
#       conn_name: invisiblemagic
#       mac: C0:25:E9:74:CD:96
#       ssid: invisiblemagic
#       wifi_sec:
#         key_mgmt: wpa-psk
#         psk: b269a69b3a6d38effeb314eb9c95d58782a09c67e54e07865ed45d69a3d96242
#       ip4: 192.168.41.4
#       gw4: 192.168.41.1
#       dns4: 192.168.41.1
#       dns4_search: syncopated.net
#       autoconnect: True
#       state: present
#       method4: manual
#     wlan1:
#       type: wifi
#       ifname: wlan1
#       conn_name: wlan1
#       mac: 9c:30:5b:d8:0c:1f
#       ssid: invisiblemagic
#       autoconnect: False
#       state: present
#       method4: disabled

host:
  packages:
    - extra-cmake-modules-git 5.240.0.r3640.44b7e47c-1
    - flashfocus 2.4.1-1
    - google-chrome 118.0.5993.117-1
    - gtk3-nocsd-git 3.0.8+2.r84.20221015.a356bf7-2
    - kvantum-theme-matcha-git r11.a3b247b-1
    - matcha-gtk-theme 2023.10.30-1
    - numix-circle-icon-theme-git 23.10.09.r0.g80235c9-1
    - numix-icon-theme-git 23.04.26.r2.gd12b26ed2-1
    - nwg-wrapper 0.1.3-2
    - poweralertd 0.2.0-2
    - pulsar-bin 1.110.0-1
    - python-backcall 0.2.0-8
    - python-xpybutil 0.0.6-5
    - sway-input-config 1.3.3-1
    - swhkd-bin 1.2.1-5
    - wev 1.0.0-12
    - wlrobs-hg r64.f72d5cb3cbbd-1
    - wlsunset 0.3.0-1
    - xcursor-breeze 1:5.27.6-1

   - a2jmidid
   - accountsservice
   - alacritty
   - alsa-plugins
   - alsa-tools
   - alsa-utils
   - aria2
   - autotiling-rs
   - avahi
   - bat
   - bind
   - blueman
   - bluez
   - bluez-hid2hci
   - bluez-libs
   - bluez-utils
   - boost-libs
   - broadcom-wl-dkms
   - btop
   - calcurse
   - calf
   - calibre
   - cmake
   - code
   - cppdap
   - cpupower
   - dhclient
   - djvulibre
   - dmidecode
   - dnsmasq
   - double-conversion
   - doxygen
   - duktape
   - efitools
   - egl-wayland
   - ethtool
   - exfatprogs
   - expac
   - eza
   - f2fs-tools
   - fastfetch
   - fd
   - ffmpegthumbnailer
   - fish
   - fmt
   - fontconfig
   - freetype2
   - fsarchiver
   - fuse-common
   - fzf
   - git
   - gnome-keyring
   - gobject-introspection
   - greetd-tuigreet
   - gst-libav
   - gst-plugins-bad
   - gst-plugins-ugly
   - gtk-engine-murrine
   - gtk-engines
   - gum
   - harfbuzz
   - haveged
   - highlight
   - htop
   - http-parser
   - hwinfo
   - imagemagick
   - intel-media-driver
   - iwd
   - jack-example-tools
   - jack2-dbus
   - jack_utils
   - jq
   - keepassxc
   - kitty
   - kvantum
   - libcups
   - libdaemon
   - libdrm
   - libdvdcss
   - libevdev
   - libglvnd
   - libgsf
   - libgudev
   - libice
   - libinput
   - libomxil-bellagio
   - libopenraw
   - libpciaccess
   - libpng
   - libproxy
   - libsm
   - libunwind
   - liburcu
   - libutempter
   - libutf8proc
   - libva-intel-driver
   - libwireplumber
   - libwnck3
   - libx11
   - libxau
   - libxcb
   - libxcursor
   - libxdamage
   - libxdmcp
   - libxext
   - libxfixes
   - libxi
   - libxkbcommon
   - libxkbcommon-x11
   - libxmu
   - libxrandr
   - libxrender
   - libxshmfence
   - libxt
   - libxxf86vm
   - lm_sensors
   - lnav
   - lsscsi
   - lua
   - lynx
   - mako
   - md4c
   - mediainfo
   - mercurial
   - mesa-utils
   - micro
   - most
   - mpv
   - mtdev
   - mtools
   - mupdf-tools
   - neovim
   - network-manager-applet
   - networkmanager-openvpn
   - nftables
   - ninja
   - nodejs
   - nss-mdns
   - ntfs-3g
   - ntp
   - obs-studio
   - obsidian
   - odt2txt
   - oniguruma
   - openscad
   - opusfile
   - os-prober
   - pacman-contrib
   - patchage
   - pavucontrol
   - polkit
   - poppler-glib
   - power-profiles-daemon
   - powerline-common
   - powerline-fonts
   - pulseaudio-alsa
   - pulseaudio-bluetooth
   - pulseaudio-jack
   - pv
   - pyside2
   - python-markupsafe
   - python-pyqt5
   - python-shiboken2
   - python-yaml
   - qjackctl
   - qscintilla-qt5
   - qt5-base
   - qt5-graphicaleffects
   - qt5-quickcontrols2
   - qt5-svg
   - qt5-tools
   - qt5-wayland
   - qt5ct
   - qt6-base
   - qt6-declarative
   - qt6-multimedia
   - qt6-tools
   - qt6-wayland
   - qt6ct
   - rhash
   - ripgrep
   - rofi
   - rsync
   - ruby-psych
   - rustup
   - rxvt-unicode
   - scdoc
   - sg3_utils
   - shared-mime-info
   - smartmontools
   - snapper
   - sof-firmware
   - swappy
   - sway
   - swaybg
   - tealdeer
   - terminology
   - thunar
   - tilda
   - transmission-cli
   - tslib
   - unzip
   - upower
   - usb_modeswitch
   - vim
   - vim-runtime
   - vorbis-tools
   - vulkan-icd-loader
   - w3m
   - wavpack
   - waybar
   - wayland
   - wf-recorder
   - wget
   - wl-clipboard
   - wofi
   - x42-plugins
   - xcb-util
   - xcb-util-image
   - xcb-util-keysyms
   - xcb-util-renderutil
   - xcb-util-wm
   - xdg-desktop-portal
   - xdg-user-dirs
   - xf86-input-libinput
   - xl2tpd
   - xorg-server
   - xorg-xdpyinfo
   - xorg-xinit
   - xorg-xinput
   - xorg-xkill
   - xorg-xprop
   - xorg-xrandr
   - xorg-xset
   - xorg-xwayland
   - zita-alsa-pcmi
   - zita-mu1
   - zoxide
   - zram-generator
   - zsh
   - zsh-theme-powerlevel10k
 - a2jmidid
 - accountsservice
 - adobe-source-han-sans-cn-fonts
 - adobe-source-han-sans-jp-fonts
 - adobe-source-han-sans-kr-fonts
 - alacritty
 - alsa-firmware
 - alsa-plugins
 - alsa-tools
 - alsa-utils
 - ansible
 - aria2
 - atool
 - autotiling-rs
 - avahi
 - awesome-terminal-fonts
 - barrier
 - bash-completion
 - bat
 - bind
 - blueman
 - bluez
 - bluez-hid2hci
 - bluez-libs
 - bluez-utils
 - boost-libs
 - broadcom-wl-dkms
 - btop
 - calcurse
 - calf
 - calibre
 - cantarell-fonts
 - cmake
 - code
 - cppdap
 - cpupower
 - dex
 - dhclient
 - djvulibre
 - dmidecode
 - dnsmasq
 - double-conversion
 - doxygen
 - duf
 - duktape
 - efitools
 - egl-wayland
 - elinks
 - ethtool
 - exfatprogs
 - expac
 - extra-cmake-modules-git
 - eza
 - f2fs-tools
 - fastfetch
 - fcft
 - fd
 - ffmpegthumbnailer
 - firewalld
 - fish
 - fmt
 - fontconfig
 - fontforge
 - foot
 - freetype2
 - fsarchiver
 - fuse-common
 - fzf
 - git
 - glances
 - gnome-keyring
 - gobject-introspection
 - greetd-tuigreet
 - gst-libav
 - gst-plugins-bad
 - gst-plugins-ugly
 - gtk-engine-murrine
 - gtk-engines
 - gum
 - harfbuzz
 - haveged
 - highlight
 - htop
 - http-parser
 - hwdetect
 - hwinfo
 - imagemagick
 - intel-media-driver
 - intel-ucode
 - inxi
 - iwd
 - jack-example-tools
 - jack2-dbus
 - jack_capture
 - jack_mixer
 - jack_utils
 - jc
 - jq
 - jupyter-nbconvert
 - keepassxc
 - kitty
 - kvantum
 - libcups
 - libdaemon
 - libdrm
 - libdvdcss
 - libevdev
 - libglvnd
 - libgsf
 - libgudev
 - libice
 - libinput
 - libjpeg-turbo
 - libomxil-bellagio
 - libopenraw
 - libpciaccess
 - libpipewire
 - libpng
 - libproxy
 - libsm
 - libunwind
 - liburcu
 - libutempter
 - libutf8proc
 - libva-intel-driver
 - libwireplumber
 - libwnck3
 - libx11
 - libxau
 - libxcb
 - libxcursor
 - libxdamage
 - libxdmcp
 - libxext
 - libxfixes
 - libxi
 - libxkbcommon
 - libxkbcommon-x11
 - libxmu
 - libxrandr
 - libxrender
 - libxshmfence
 - libxt
 - libxxf86vm
 - lm_sensors
 - lnav
 - lsb-release
 - lsscsi
 - lua
 - lynx
 - mako
 - md4c
 - mediainfo
 - meld
 - mercurial
 - mesa-utils
 - mesa-vdpau
 - meson
 - micro
 - modemmanager
 - most
 - mpv
 - mtdev
 - mtools
 - mupdf-tools
 - nano-syntax-highlighting
 - neovim
 - netctl
 - network-manager-applet
 - networkmanager
 - networkmanager-openvpn
 - nftables
 - ninja
 - node-gyp
 - nodejs
 - noto-fonts
 - noto-fonts-cjk
 - noto-fonts-emoji
 - npm
 - nss-mdns
 - ntfs-3g
 - ntp
 - obs-studio
 - obsidian
 - odt2txt
 - oniguruma
 - opencl-clover-mesa
 - opencl-rusticl-mesa
 - opendesktop-fonts
 - openscad
 - opusfile
 - os-prober
 - pacman-contrib
 - parallel
 - patchage
 - pavucontrol
 - perl-image-exiftool
 - plasma-wayland-protocols
 - polkit
 - poppler-glib
 - postgresql-libs
 - power-profiles-daemon
 - powerline-common
 - powerline-fonts
 - pulseaudio-alsa
 - pulseaudio-bluetooth
 - pulseaudio-jack
 - pulsemixer
 - pv
 - pyside2
 - python-annotated-types
 - python-asttokens
 - python-autocommand
 - python-babel
 - python-binaryornot
 - python-boolean.py
 - python-build
 - python-chardet
 - python-charset-normalizer
 - python-click
 - python-debian
 - python-defusedxml
 - python-docutils
 - python-i3ipc
 - python-idna
 - python-imagesize
 - python-inflect
 - python-installer
 - python-ipykernel
 - python-jaraco.context
 - python-jaraco.functools
 - python-jaraco.text
 - python-jedi
 - python-jinja
 - python-jupyter-client
 - python-license-expression
 - python-mako
 - python-markdown
 - python-markupsafe
 - python-marshmallow
 - python-more-itertools
 - python-ordered-set
 - python-packaging
 - python-pillow
 - python-pydantic
 - python-pydantic-core
 - python-pygments
 - python-pyproject-hooks
 - python-pyqt5
 - python-pytz
 - python-requests
 - python-setuptools
 - python-shiboken2
 - python-six
 - python-snowballstemmer
 - python-sphinx
 - python-sphinx-alabaster-theme
 - python-sphinxcontrib-applehelp
 - python-sphinxcontrib-devhelp
 - python-sphinxcontrib-htmlhelp
 - python-sphinxcontrib-jsmath
 - python-sphinxcontrib-qthelp
 - python-sphinxcontrib-serializinghtml
 - python-tomli
 - python-tqdm
 - python-traitlets
 - python-trove-classifiers
 - python-urllib3
 - python-validate-pyproject
 - python-wheel
 - python-xcffib
 - python-xlib
 - python-yaml
 - qjackctl
 - qscintilla-qt5
 - qt5-base
 - qt5-graphicaleffects
 - qt5-quickcontrols2
 - qt5-svg
 - qt5-tools
 - qt5-wayland
 - qt5-x11extras
 - qt5ct
 - qt6-base
 - qt6-declarative
 - qt6-multimedia
 - qt6-tools
 - qt6-wayland
 - qt6ct
 - ranger
 - rebuild-detector
 - reflector
 - reuse
 - rhash
 - ripgrep
 - ripgrep-all
 - rofi
 - rsync
 - rtirq
 - rtkit
 - ruby-psych
 - rustup
 - rxvt-unicode
 - scdoc
 - sg3_utils
 - shared-mime-info
 - smartmontools
 - snapper
 - snappy
 - sof-firmware
 - swappy
 - sway
 - swaybg
 - tealdeer
 - terminator
 - terminology
 - thunar
 - tilda
 - transmission-cli
 - tslib
 - ttf-bitstream-vera
 - ttf-dejavu
 - ttf-firacode-nerd
 - ttf-font-awesome
 - ttf-input
 - ttf-jetbrains-mono
 - ttf-liberation
 - ttf-meslo-nerd
 - ttf-opensans
 - ttf-ubuntu-font-family
 - ueberzug
 - unrar
 - unzip
 - upower
 - usb_modeswitch
 - vim
 - vim-runtime
 - vorbis-tools
 - vulkan-headers
 - vulkan-icd-loader
 - vulkan-intel
 - w3m
 - wavpack
 - waybar
 - wayland
 - wayland-protocols
 - wf-recorder
 - wget
 - wl-clipboard
 - wofi
 - x42-plugins
 - xcb-util
 - xcb-util-image
 - xcb-util-keysyms
 - xcb-util-renderutil
 - xcb-util-wm
 - xdg-desktop-portal
 - xdg-desktop-portal-wlr
 - xdg-user-dirs
 - xf86-input-libinput
 - xl2tpd
 - xorg-server
 - xorg-xdpyinfo
 - xorg-xinit
 - xorg-xinput
 - xorg-xkill
 - xorg-xprop
 - xorg-xrandr
 - xorg-xset
 - xorg-xwayland
 - zita-alsa-pcmi
 - zita-mu1
 - zoxide
 - zram-generator
 - zsh
 - zsh-theme-powerlevel10k
