---
# defaults file for docker

# docker: "defaults/main.yml"

docker:
  storage: /var/lib/docker

use_docker: False

docker_packages:
  fedora:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - docker-buildx-plugin
  debian:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin