---

# - name: Import primary key - chaotic
#   command: pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
#   register: importkey
#   changed_when: false
#
# - name: Sign primary key - chaotic
#   command: pacman-key --lsign-key 3056513887B78AEB
#   register: signkey
#   changed_when: false

- name: Install chaotic keyring and mirrorlist
  shell: |
    pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm && \
    pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
  changed_when: false

- name: Check pacman.conf contents
  command: cat /etc/pacman.conf
  register: pacman_conf_output
  changed_when: false

- name: Add chaotic mirror list
  copy:
    src: etc/pacman.d/chaotic-mirrorlist
    dest: /etc/pacman.d/chaotic-mirrorlist
    owner: root
    group: root
    mode: '0644'
    backup: True

- name: Add repository to pacman.conf
  lineinfile:
    path: /etc/pacman.conf
    line: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
    insertafter: EOF
  when: "'[chaotic-aur]' not in pacman_conf_output.stdout"
  changed_when: false
  failed_when: false
  register: pacman_conf_add

- name: Update cache
  pacman:
    update_cache: True
    upgrade: False
