---

- block:

    - name: Add Hasicorp repository
      shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

    - name: Install vagrant requirements
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - '@Development Tools'
        - cmake
        - libguestfs-tools-c
        - libvirt-devel
        - libxml2-devel
        - libxslt-devel
        - rsync
        - ruby
        - ruby-devel
        - zlib-devel

    - name: Install vagrant
      dnf:
        name: vagrant
        state: present
        update_cache: yes

  when: ansible_distribution == 'Fedora'
  tags: ['packages']

- block:

    - name: Install vagrant
      pacman:
        name: vagrant
        state: present
        force: yes
        extra_args: --noconfirm

  when: ansible_distribution == 'Archlinux'
  tags: ['packages']
