---

# - name: install sxhkd
#   aur:
#     use: paru
#     name: sxhkd
#     state: present
#   become: False
#   tags: ["packages"]

- name: Install SXHKD package
  block:
    - name: Install SXHKD on Arch Linux
      pacman:
        name: "{{ sxhkd_packages.archlinux }}"
        state: present
      when: ansible_distribution == "Archlinux"

    - name: Install SXHKD on Fedora
      dnf:
        name: "{{ sxhkd_packages.fedora }}"
        state: present
      when: ansible_distribution == "Fedora"

- name: Install sxhkd reload function
  copy:
    content: |
      #!/usr/bin/env bash
      # shellcheck disable=CODE

      function run {
        if pgrep -x -f "$1" ; then
          pkill -9 $@&
          sleep 1
          $@&
        else
          sleep 1
          $@&
        fi
      }

      run "sxhkd"

      sleep 0.5
    dest: "/usr/local/bin/reload-sxhkd.sh"
    owner: "{{ user.name }}"
    mode: '0755'

- name: Ensure SXHKD configuration directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/sxhkd"
    state: directory
    mode: '0755'
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

# - name: Create sxhkd config folder
#   file:
#     path: "{{ user.home }}/.config/sxhkd"
#     state: directory
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"

- name: Copy SXHKD configuration file
  template:
    src: sxhkdrc.j2
    dest: "{{ ansible_env.HOME }}/.config/sxhkd/sxhkdrc"
    mode: '0644'
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  notify: Reload sxhkd

# - name: Install sxhkd keybindings
#   template:
#     src: "sxhkdrc.j2"
#     dest: "{{ user.home }}/.config/sxhkd/sxhkdrc"
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"
#     mode: '0644'
#     backup: false
#   notify:
#     - Reload i3
#     - Reload sxhkd
#   tags: ["profile", "keybindings"]
