---

- name: Create timesyncd.conf.d directory
  file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory

- name: set ntp servers in timesyncd.conf
  copy:
    src: etc/systemd/timesyncd.conf.d/local.conf
    dest: /etc/systemd/timesyncd.conf.d/local.conf
    mode: '0644'
    backup: yes
  register: timesyncd_conf
  notify: enable systemd-timesyncd service

- name: Sync hwclock
  shell: |
    timedatectl set-ntp true && \
    sleep 4 && \
    hwclock --systohc
  when: timesyncd_conf.changed
