---

share:
  nfs:
    parent: "/srv"
    exports:
      - storage

chaoticrepo: True
# TODO: test whether or not this variable will overwrite the defaults with nothing..
# docker:
  # service: 'enabled'
  # storage: /var/lib/docker
  # nvidia: True

nvidia:

dm: False
browser: "google-chrome-stable"
terminal: "kitty"
audio: "jack"

# barrier:
#   client:
#     name: ninjabot
#     server: '[tinybot]:24800'
#   client:
#     name: ninjabot
#     server: '[soundbot]:24801'
x:
  autostart:
    - bash ~/.screenlayout/ninjabot.sh

i3:
  autostart:
    - "barrierc -f --debug INFO --name ninjabot --disable-crypto [tinybot]:24800"
    - "sleep 0.5"
    - "barrierc -f --debug INFO --name ninjabot --disable-crypto [soundbot]:24801"
  tray_output: 'primary'
  assignments: 'default'
  workspaces: 'default'
  keybindings: 'default'

# network_interfaces:
#   - device: eth0
#     type: ethernet
#     ifname: eth0
#     conn_name: eth0
#     mac: bc:5f:f4:0e:bb:b5
#     ip4: 192.168.41.44/24
#     gw4: 192.168.41.1
#     dns4:
#       - 192.168.41.41
#       - 192.168.41.1
#     dns4_search: syncopated.net
#     autoconnect: True
#     state: present
#     method4: manual
#   - device: eth1
#     type: ethernet
#     ifname: eth1
#     conn_name: audio
#     mac: bc:5f:f4:0e:bb:b3
#     ip4: 192.168.36.3/28
#     autoconnect: True
#     state: present
#     method4: manual

host:
  kernel:
    - linux
    - linux-headers
    - linux-lts
    - linux-lts-headers
  xorg:
    video:
    # intel:
      - intel-gpu-tools
      - intel-media-driver
      - intel-ucode
      - libva-intel-driver
      - libva-mesa-driver
      - libvdpau-va-gl-i965
      - vulkan-headers
      - vulkan-icd-loader
      - vulkan-intel
      - xf86-video-intel
    # nvidia:
      - lib32-nvidia-470xx-utils
      - lib32-opencl-nvidia-470xx
      - lib32-opencl-rusticl-mesa
      - libnvidia-container
      - libnvidia-container-tools
      - libva-nvidia-driver
      - nvidia-470xx-dkms
      - nvidia-470xx-settings
      - nvidia-470xx-utils
      - nvidia-container-runtime
      - nvidia-container-toolkit
      # - nvidia-docker
      - nvidia-docker-compose
    # opengl:
      - libva-utils
      - libvdpau-va-gl
      - mesa-amber
      - mesa-utils
      - mesa-vdpau
      - vdpauinfo
    # opencl:
      - opencl-clover-mesa
      - opencl-nvidia-470xx
      - opencl-rusticl-mesa

# host:
#   packages:
#     audio:
#       - a2jmidid
#       - accountsservice
#       - alsa-card-profiles
#       - alsa-firmware
#       - alsa-plugins
#       - alsa-tools
#       - alsa-utils
#       - ambdec
#       - bitwig-studio
#       - bluez
#       - bluez-hid2hci
#       - bluez-libs
#       - bluez-utils
#       - jack2
#       - jack2-dbus
#       - jack-example-tools
#       - jack_capture
#       - jack_utils
#       - jacktrip
#       - libwireplumber
#       - mixxx
#       - mpg123
#       - opusfile
#       - osc2midi
#       - pavucontrol
#       - pipewire
#       - pulseaudio
#       - pulseaudio-alsa
#       - pulseaudio-bluetooth
#       - pulseaudio-jack
#       - pulsemixer
#       - qmidiarp
#       - qmidinet
#       - qsampler
#       - rnnoise
#       - sndio
#       - vmpk
#       - vorbis-tools
#       - zita-alsa-pcmi
#     fonts:
#       - adobe-source-han-sans-cn-fonts
#       - adobe-source-han-sans-jp-fonts
#       - adobe-source-han-sans-kr-fonts
#       - arc-icon-theme
#       - awesome-terminal-fonts
#       - cachyos-nord-gtk-theme-git
#       - cantarell-fonts
#       - noto-color-emoji-fontconfig
#       - noto-fonts
#       - noto-fonts-cjk
#       - noto-fonts-emoji
#       - numix-circle-icon-theme-git
#       - numix-icon-theme-git
#       - opendesktop-fonts
#       - ttf-bitstream-vera
#       - ttf-dejavu
#       - ttf-firacode-nerd
#       - ttf-font-awesome
#       - ttf-input
#       - ttf-jetbrains-mono
#       - ttf-liberation
#       - ttf-meslo-nerd
#       - ttf-opensans
#       - ttf-ubuntu-font-family
#     codecs:
#       - gst-libav
#       - gst-plugin-pipewire
#       - gst-plugins-bad
#       - gst-plugins-ugly
#     terminal:
#       - alacritty
#       - aria2
#       - asciiquarium-transparent-git
#       - bash-completion
#       - bat
#       - bottom
#       - btop
#       - eza
#       - fd
#       - figlet
#       - github-cli
#       - gitui
#       - guake
#       - gum
#       - htop
#       - kitty
#       - kitty-shell-integration
#       - kitty-terminfo
#       - lnav
#       - most
#       - ncdu
#       - neofetch
#       - nvtop
#       - ranger
#       - ripgrep
#       - ripgrep-all
#       - rsync
#       - smartmontools
#       - termdown
#       - terminator
#       - tilda
#       - tree
#       - ueberzug
#       - w3m
#       - wget
#       - yadm
#       - zoxide
#     design:
#       - cef-minimal-obs-bin
#       - darktable
#       - figma-linux-bin
#       - gimp
#       - imagemagick
#     gtk:
#       - gtk-doc
#       - gtk-engine-murrine
#       - gtk-engines
#       - gtk-update-icon-cache
#       - gtksourceview3
#       - gtkspell3
#     qt:
#       - qscintilla-qt5
#       - qt5-base
#       - qt5-declarative
#       - qt5-location
#       - qt5-tools
#       - qt5-x11extras
#       - qt5ct
#       - qt6-declarative
#       - qt6-multimedia
#       - qt6-tools
#       - qt6-wayland
#       - qt6ct
#     kvantum:
#       - kvantum
#       - kwindowsystem5
#     i3:
#       - i3-wm
#       - i3blocks
#       - i3lock-color
#       - i3status
#       - i3status-rust
#     desktop:
#       - arandr
#       - aspell-en
#       - autorandr
#       - barrier
#       - cachy-browser
#       - cachyos-hello
#       - cachyos-packageinstaller
#       - cachyos-rate-mirrors
#       - cachyos-settings
#       - dconf
#       - dunst
#       - ffmpeg4.4
#       - ffmpegthumbnailer
#       - firewalld
#       - fsarchiver
#       - fuse3
#       - fuse-common
#       - gconf
#       - geoclue
#       - gnome-common
#       - gnome-keyring
#       - gnuplot
#       - google-chrome
#       - gpick
#       - graphicsmagick
#       - grsync
#       - hexchat
#       - sd
#       - imv
#       - inxi
#       - jc
#       - keepassxc
#       - maim
#       - micro
#       - mpv
#       - network-manager-applet
#       - numlockx
#       - octopi
#       - paru
#       - pass
#       - polybar
#       - profile-sync-daemon
#       - qpdf
#       - qutebrowser
#       - redshift
#       - rofi
#       - seahorse
#       - slop
#       - sxiv
#       - teiler-git
#       - thunar
#       - thunar-archive-plugin
#       - thunar-volman
#       - unrar
#       - unzip
#       - vlc
#       - wmctrl
#       - wmfocus
#       - yt-dlp
#     development:
#       - asp
#       - bmake
#       - cmake
#       - cython
#       - dconf-editor
#       - devdocs-desktop
#       - devtools
#       - docker
#       - docker-compose
#       - electron25
#       - git-meld
#       - gitflow-zshcompletion-avh
#       - lazydocker-bin
#       - meld
#       - nano-syntax-highlighting
#       - neovim
#       - neovim-symlinks
#       - nodejs
#       - npm
#       - obsidian
#       - postgresql-libs
#       - pulsar-bin
#       - rubygems
#       - subversion
#       - vim-runtime
#       - virt-install
#       - virt-manager
#       - virt-viewer
#     python:
#       - python
#       - python-adblock
#       - python-annotated-types
#       - python-autocommand
#       - python-cairo
#       - python-cffi
#       - python-defusedxml
#       - python-fastjsonschema
#       - python-inflect
#       - python-jaraco.context
#       - python-jaraco.functools
#       - python-jaraco.text
#       - python-jinja
#       - python-lxml
#       - python-mako
#       - python-markdown
#       - python-markupsafe
#       - python-more-itertools
#       - python-numpy
#       - python-ordered-set
#       - python-packaging
#       - python-pillow
#       - python-pip
#       - python-platformdirs
#       - python-psutil
#       - python-pydantic
#       - python-pydantic-core
#       - python-pyqt5
#       - python-pyqt5-sip
#       - python-requests
#       - python-ruamel-yaml
#       - python-setuptools
#       - python-tomli
#       - python-trove-classifiers
#       - python-typing_extensions
#       - python-validate-pyproject
#       - python-yaml
#     network:
#       - iwd
#       - modemmanager
#       - networkmanager
#       - networkmanager-openvpn
#       - ntp
#     kernal:
#       - linux-cachyos
#       - linux-cachyos-headers
#     system:
#       - apr
#       - aribb24
#       - asio
#       - asp
#       - autoconf-archive
#       - bc
#       - beep
#       - bind
#       - bpftune-git
#       - broadcom-wl-dkms
#       - btrfs-assistant-git
#       - btrfsmaintenance
#       - cachyos-ananicy-rules
#       - cachyos-hooks
#       - cachyos-kernel-manager
#       - cachyos-keyring
#       - cachyos-mirrorlist
#       - cachyos-v3-mirrorlist
#       - cachyos-v4-mirrorlist
#       - chwd
#       - chwd-db
#       - cpupower
#       - dhclient
#       - dhcpcd
#       - dmidecode
#       - dnsmasq
#       - efitools
#       - ethtool
#       - exfatprogs
#       - f2fs-tools
#       - go
#       - grub
#       - grub-hook
#       - help2man
#       - hwdetect
#       - hwinfo
#       - lsb-release
#       - mkinitcpio
#       - msgpack-c
#       - mtools
#       - netctl
#       - ntfs-3g
#       - os-prober
#       - pacman-contrib
#       - parallel
#       - pcurses
#       - pdfjs
#       - pv
#       - rebuild-detector
#       - reflector
#       - rtkit
#       - rustup
#       - upower
#       - usb_modeswitch
#       - vte3
#       - vte-common
#       - xarchiver
#       - zeromq
#     xorg:
#       - xcb-util-cursor
#       - xclip
#       - xdg-dbus-proxy
#       - xdg-desktop-portal
#       - xdg-user-dirs
#       - xdot
#       - xdotool
#       - xf86-input-libinput
#       - xf86-input-wacom
#       - xfconf
#       - xininfo-git
#       - xkeyboard-config
#       - xkill-shortcut
#       - xl2tpd
#       - xorg-bdftopcf
#       - xorg-fonts-alias-75dpi
#       - xorg-fonts-alias-100dpi
#       - xorg-fonts-alias-cyrillic
#       - xorg-fonts-alias-misc
#       - xorg-fonts-misc
#       - xorg-iceauth
#       - xorg-mkfontscale
#       - xorg-server
#       - xorg-server-common
#       - xorg-sessreg
#       - xorg-smproxy
#       - xorg-x11perf
#       - xorg-xbacklight
#       - xorg-xcmsdb
#       - xorg-xcursorgen
#       - xorg-xdpyinfo
#       - xorg-xdriinfo
#       - xorg-xev
#       - xorg-xgamma
#       - xorg-xhost
#       - xorg-xinit
#       - xorg-xinput
#       - xorg-xkbevd
#       - xorg-xkbutils
#       - xorg-xkill
#       - xorg-xlsatoms
#       - xorg-xlsclients
#       - xorg-xlsfonts
#       - xorg-xpr
#       - xorg-xrandr
#       - xorg-xrefresh
#       - xorg-xsetroot
#       - xorg-xvinfo
#       - xorg-xwd
#       - xorg-xwininfo
#       - xorg-xwud
#       - xterm
#     kvm:
#       - qemu-audio-alsa
#       - qemu-audio-dbus
#       - qemu-audio-jack
#       - qemu-audio-oss
#       - qemu-audio-pa
#       - qemu-audio-pipewire
#       - qemu-audio-sdl
#       - qemu-audio-spice
#       - qemu-base
#       - qemu-block-curl
#       - qemu-block-dmg
#       - qemu-block-gluster
#       - qemu-block-iscsi
#       - qemu-block-nfs
#       - qemu-block-ssh
#       - qemu-chardev-baum
#       - qemu-chardev-spice
#       - qemu-common
#       - qemu-desktop
#       - qemu-docs
#       - qemu-emulators-full
#       - qemu-full
#       - qemu-hw-display-qxl
#       - qemu-hw-display-virtio-gpu
#       - qemu-hw-display-virtio-gpu-gl
#       - qemu-hw-display-virtio-gpu-pci
#       - qemu-hw-display-virtio-gpu-pci-gl
#       - qemu-hw-display-virtio-vga
#       - qemu-hw-display-virtio-vga-gl
#       - qemu-hw-s390x-virtio-gpu-ccw
#       - qemu-hw-usb-host
#       - qemu-hw-usb-redirect
#       - qemu-hw-usb-smartcard
#       - qemu-img
#       - qemu-pr-helper
#       - qemu-system-aarch64
#       - qemu-system-alpha
#       - qemu-system-alpha-firmware
#       - qemu-system-arm
#       - qemu-system-arm-firmware
#       - qemu-system-avr
#       - qemu-system-cris
#       - qemu-system-hppa
#       - qemu-system-hppa-firmware
#       - qemu-system-loongarch64
#       - qemu-system-m68k
#       - qemu-system-microblaze
#       - qemu-system-microblaze-firmware
#       - qemu-system-mips
#       - qemu-system-nios2
#       - qemu-system-or1k
#       - qemu-system-ppc
#       - qemu-system-ppc-firmware
#       - qemu-system-riscv
#       - qemu-system-riscv-firmware
#       - qemu-system-rx
#       - qemu-system-s390x
#       - qemu-system-s390x-firmware
#       - qemu-system-sh4
#       - qemu-system-sparc
#       - qemu-system-sparc-firmware
#       - qemu-system-tricore
#       - qemu-system-x86
#       - qemu-system-x86-firmware
#       - qemu-system-xtensa
#       - qemu-tests
#       - qemu-tools
#       - qemu-ui-curses
#       - qemu-ui-dbus
#       - qemu-ui-egl-headless
#       - qemu-ui-gtk
#       - qemu-ui-opengl
#       - qemu-ui-sdl
#       - qemu-ui-spice-app
#       - qemu-ui-spice-core
#       - qemu-user
#       - qemu-vhost-user-gpu
#     dependencies:
#       # - cachyos-fish-config
#       # - cachyos-i3wm-settings
#       # - cachyos-micro-settings
#       # - cachyos-picom-config
#       # - cachyos-zsh-config
#       - cjson
#       - docbook-xml
#       - docbook-xsl
#       - duf
#       - edk2-ovmf
#       - egl-wayland
#       - enchant
#       - fastfetch
#       - glances
#       - glew
#       - gobject-introspection
#       - gperftools
#       - harfbuzz
#       - harfbuzz-icu
#       - haveged
#       - hyphen
#       - intltool
#       - itstool
#       - libajantv2
#       - libdatachannel
#       - libdrm
#       - libdvbpsi
#       - libdvdcss
#       - libebml
#       - libgsf
#       - libgtop
#       - libguestfs
#       - libheif
#       - libical
#       - libjuice
#       - libluv
#       - libmanette
#       - libmatroska
#       - libmbim
#       - libmfx
#       - libmm-glib
#       - libmysofa
#       - libnm
#       - libopenraw
#       - libpaper
#       - libpipewire
#       - libprocps
#       - libqmi
#       - librist
#       - libsodium
#       - libsoup3
#       - libsysprof-capture
#       - libtar
#       - libtermkey
#       - libunwind
#       - libupnp
#       - libutf8proc
#       - libvterm
#       - libwnck3
#       - libwpe
#       - lsscsi
#       - luajit
#       - mallard-ducktype
#       - mbedtls
#       - mbedtls2
#       - moc
#       - nftables
#       - nlohmann-json
#       - nss-mdns
#       - oniguruma
#       - peg
#       - perl-anyevent-i3
#       - poppler-glib
#       - power-profiles-daemon
#       - protobuf
#       - qrcodegencpp-cmake
#       - rhash
#       - rpcsvc-proto
#       - semver
#       - serd
#       - sg3_utils
#       - snapper
#       - snappy
#       - sof-firmware
#       - stunnel
#       - suitesparse
#       - swig
#       - tree-sitter
#       - unibilium
#       - webkit2gtk
#       - websocketpp
#       - woff2
#       - wpebackend-fdo
#       - yelp-tools
#       - yelp-xsl
