---

- name: DAW Tasks
  debug:
    msg: "Starting DAW role tasks"

- name: Ensure application directories exist
  file:
    path: "{{ application_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ application_directory_definitions }}"
  check_mode: no
  tags: ['profile']

- import_tasks:
    file: controllers/main.yml
  tags: ['controllers']

- import_tasks:
    file: analysis/main.yml
  tags: ['analysis']

- import_tasks:
    file: players/main.yml
  tags: ['players']

- import_tasks:
    file: editors/main.yml
  tags: ['editors']

- import_tasks:
    file: livecoding/main.yml
  tags: ['livecoding']
